### ISSUE TITLE
"Open With" hides console applications on Windows

### ISSUE THREAD

**Issue by vhanla** [SideBarEnhancements-org/SideBarEnhancements#255]
The Open with Command Line option executes the cmd.exe but it is hidden, I tried with other console applications and they are executed hidden.

Is there any way to make them visible?

I created a simple console application to open the selected file's directory in cmd.exe.

_OS: Windows 8.1 x64_
_SublimeText 3: Build 3083_

**Comment by titoBouzout** [comment]
Please see https://github.com/SideBarEnhancements-org/SideBarEnhancements/issues/336
