### ISSUE TITLE
Opening folder 

### ISSUE THREAD

**Issue by leesei** [SideBarEnhancements-org/SideBarEnhancements#263]
I would like to add entry to `Side Bar.sublime-menu` to open folder with file browser (say `nemo`).
I see an extension filter, is there a filter for folders?
The current `Open/Run` opens a terminal at the folder withoud `cd`-ing into the folder (Cinnamon/Arch).

<hr/>

**Edit**:
A workaround (at least for Linux) is to use "Open in Browser".

**Comment by titoBouzout** [comment]
Right click -> open in browser, works with folders too

**Comment by leesei** [comment]
Oh, thanks for the pointer.
I thought that browser meant web browsers.

**Comment by titoBouzout** [comment]
Yes it means web browser, you are looking for "reveal" then.

**Comment by titoBouzout** [comment]
I can add a filter for directories if you need it

**Comment by leesei** [comment]
I found that "open in browser" command works as I intended.
I'm on Linux Mint and did not set `default_browser`/`portable_browser`.
Are you calling `xdg-open`?

**Comment by titoBouzout** [comment]
Yes :)

https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py#L1826

**Comment by leesei** [comment]
Then I suggest replacing the menu item as "Open", and the setting as
"open_exec".
Does this make sense for other platform?

Anyway my original issue is fixed indeed, it's just how to make this
feature more easily discoverable.
However I'm not sure if a generic UI shell open is intended in the first
place.

**Comment by titoBouzout** [comment]
It makes non sense because the menuitem is intended to be used to open a Web Browser, when everything fails (no web-browser found, no web-browser set), it calls to xdg-open on Linux.

I can add a menuitem named "Run" only for Linux just bellow "open/run". It makes sense to call xdg-open on all Linuxes?

**Comment by leesei** [comment]
I see, I'm using a fallback case. But that works for me :-P.
I do not recommend adding special handling for Linux.

That said, how about renaming menuitem "Run" to "Open/Run" which
- call sh/cmd for files
- call xdg-open/explorer.exe/open for folders

Or we can just rename "Run" as "Open", and define "open_file_exec",
"open_folder_exec" in settings.
This allows for more customization and more inline with the behavior of a
file browser (double click to open with default app, customized opening
with "Open with").

**Comment by titoBouzout** [comment]
OKei Im gonna revisit this once time allows, thanks!

**Comment by iwfmp** [comment]
I second this request.
I want to open the location (directory path) of the file in both terminal and a file explorer.
Since I don't usually (e.g. ever) use finder, the reveal option doesn't work for me (I use double-commander), and I need the directory path cd'd to.

further, since I don't usually use a mouse, right-clicking is far from convenient.
I would like to have it in the command panel, after adding it to the .sublime-commands file.

**Comment by ihorvorotnov** [comment]
Slightly related question. I see `"use_powershell": true` options in package settings, which allows us to use regular cmd on Windows or a PowerShell. However, I can't find a way to tell Open/Run command to use my custom terminal (mintty, cmder, cygwin, git bash etc - there are some options). Something like `"use_shell": "C:/some/custom/path/mintty.exe"`?

**Comment by kevinSuttle** [comment]
Sometimes I would like to open a folder in Tower, FileMerge/Kaleidoscope, etc. Is there way to tell SBE to use a folder file type?

**Comment by cjaoude** [comment]
Anyone else having an issue with Reveal opening the Finder? It used to reveal in sidebar. I haven't changed anything. I rely on Reveal in sidebar heavily, it's a real bummer.

**Comment by titoBouzout** [comment]
@cjaoude is named "locate" not "reveal", locate is to find out where in sidebar is and reveal is to show it up in the file system with the in os file manager.

**Comment by titoBouzout** [comment]
> Slightly related question. I see `"use_powershell": true` option in package settings, which allows us to use standard cmd on Windows or a PowerShell. However, I can't find a way to tell Open/Run command to use my custom terminal (mintty, cmder, cygwin, git bash etc - there are some options). Something like `"use_shell": "C:/some/custom/path/mintty.exe"`?

I just added a setting named "use_command" which in theory should fix this issue as you can launch any program if is on the path, please let me know if you have issues with it
