### ISSUE TITLE
What's the format of the "args" array for the application?

### ISSUE THREAD

**Issue by madastro** [SideBarEnhancements-org/SideBarEnhancements#317]
I've created the following Open with... command:

``` json
{
    "caption": "Command Prompt",
    "id": "side-bar-files-open-with-cmd",

    "command": "side_bar_files_open_with",
    "args": {
        "paths": [],
        "application": "C:\\bin\\console2\\Console.exe",
        "extensions": "",
        "args": []
    }
},
```

and the application's command to open a folder is `console -d path`.

I have tried testing with `["%1"]`, `["-d %1"]`, `["-d","%1"]` for the second set of "args", but all of them does not seem to work, so I would appreciate any pointers.

**Comment by titoBouzout** [comment]
is a list, the current selected item is passed as last argument, so you can omit the %1

**Comment by dogancelik** [comment]
Is there a way to pass the file/folder path how we want?
Maybe custom variables, like: `$FILE_DIR_PATH`, `$FILE_FILENAME`, `$FILE_FULL_PATH`, `$FILE_EXTENSION`, etc.

I use ConEmu for Console program and not PowerShell and I need to start ConEmu with arguments in right order.

```json
{
  "caption": "ConEmu",
  "id": "side-bar-files-open-with-conemu",

  "command": "side_bar_files_open_with",
  "args": {
            "paths": [],
            "application": "E:/Portable/ConEmu/ConEmu64.exe",
            "extensions":"",
            "args":["-Dir %1", "-run", "-cur_console:n"]
          },
  "open_automatically": false
},
```

**Comment by titoBouzout** [comment]
Sounds like a good idea! This is the relevant part, it would be pretty easy to iterate the list and replace as desired https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py#L302

**Comment by titoBouzout** [comment]
This been implemented already

**Comment by dogancelik** [comment]
```json
{
  "caption": "XYplorer",
  "id": "ow-xyplorer",
  "command": "side_bar_files_open_with",
  "args": {
      "paths": [],
      "application": "D:/Portable/XYplorer/XYplorer.exe",
      "extensions": "",
      "args": ["$DIRNAME"]
    },
  "open_automatically" : false
},
```

I can't use XYplorer because SBE appends `$PATH` as last argument at [SideBar.py#L323](https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py#L323)

SBE should use a default args and user should override it that instead.

* Default args: `["$PATH"]`
* User defined app args: `["$DIRNAME"]`

SBE should not append `$PATH` as second argument.
