### ISSUE TITLE
string not in pwd

### ISSUE THREAD

**Issue by sumnermic** [SideBarEnhancements-org/SideBarEnhancements#321]
Hello,

I received an error in terminal that when I 'Copy as Text' > 'Path':
`/Users/mic/Desktop/Ex_Files_LReact_js_2016/Exercise Files/Ch06/06_02/start`

terminal receives an error `string not in pwd`.

This was solved by adding a backslash `\` (thus escaping the space character) in the space found in `Exercise Files`.
`/Users/mic/Desktop/Ex_Files_LReact_js_2016/Exercise\ Files/Ch06/06_02/start`

May we have a fix for this please?

**Comment by titoBouzout** [comment]
Ill accept a pull request, basically you duplicate command  'Copy as Text' > 'Path': as  'Copy as Text' > 'Path Escape': and just modify the string before copying to clipboard

**Comment by sumnermic** [comment]
Sorry about that but is it okay if you do this @titoBouzout ? I just wanted to explain that when I have a folder/directory with a 'space' then the 'copied path' did not escape the 'space' as `\ `.
