### ISSUE TITLE
CTRL + K + B Does Not Open Sidebar

### ISSUE THREAD

**Issue by vongoh** [SideBarEnhancements-org/SideBarEnhancements#326]
Strangely, with some of my Sublime Text 3 projects the sidebar will not open with `CTRL+K+B'.   

With these projects the hotkey combo is simply dead.   The only way I have found so far is to go to 'File > Open Folder' to open up a new instance of ST3.   Then the hotkey opens up the sidebar fine.

Only problem with this is that this folder now opens up without any of my project settings.

I havent been able to find any common denominator as to what might be causing this. Thoughts?  Thanks!

**Comment by titoBouzout** [comment]
Maybe some syntax related setting is overwriting the key command.
