### ISSUE TITLE
Find files named not working (ubuntu, windows)

### ISSUE THREAD

**Issue by dagomar** [SideBarEnhancements-org/SideBarEnhancements#330]
Hi, 

this hasn't been working for me for a long time, when it did I really liked it and used it a lot. The Instant File Search tab opens, I can type text after "Type to search: ", but I never get any results.

My system:
Ubuntu (15:10)
Sublime 3 build 3122
Home folder is encrypted.

I did a clean install of SideBarEnhancements, in a completely clean sublime install (to make sure it was no conflict). Not working. If there is anything I can do to debug this problem please let me know. I couldn''t find anything in the console.

(update: description of the problem)
(update: Issue title as it's now confirmed on Windows as well)

**Comment by Rockson** [comment]
I've the same problem. It's not working also on windows.

**Comment by dabros** [comment]
Same here, whatever you type, no results ever appear

Windows 10 Pro
Sublime build 3083

**Comment by AlexVentura** [comment]
Is there a way to execute `Find Files Named...` from the keyboard in OS X?

**Comment by AlexVentura** [comment]
@titoBouzout Great, that works, than you so much!
