### ISSUE TITLE
Edit browser list

### ISSUE THREAD

**Issue by glaszczyk** [SideBarEnhancements-org/SideBarEnhancements#333]
How can I change browser list?
I would like to replace one browser with different one.

Thank you.

**Comment by titoBouzout** [comment]
This is the function, 
https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py#L1660

Look for the 'if browser == "chrome"' ... etc, then you see another if for the platform. 

And here you have the menuitems

https://github.com/titoBouzout/SideBarEnhancements/blob/st3/Side%20Bar.sublime-menu#L60
