### ISSUE TITLE
How to double click to 'open / run' a specific file (like a .bat file)?

### ISSUE THREAD

**Issue by QS20199** [SideBarEnhancements-org/SideBarEnhancements#336]
At present I can right click and select the `open / run` command to run a `.bat` file, but it's a little inconvenient.

So, how can I double click to run a `.bat` file directly?

**Comment by titoBouzout** [comment]
Looks like the following configuration into the "open with.." -> "edit applications" works for me:

```
{
	"caption": "Run bat file on double click",
	"id": "side-bar-files-open-bat",
	"command": "side_bar_files_open_with",
	"args": {
						"paths": [],
						"application": "C:\\Windows\\System32\\cmd.exe",
						"extensions":"bat", //any file with extension
						"args":["/k","start", ""]
			},
	"open_automatically" : true // will close the view/tab and launch the application
},
```

**Comment by titoBouzout** [comment]
I suggest to not use that kind of thing because automatically running a bat file in a text editor(place where you expect to the edit the content) at doubleclick could be a dangerous thing to do.
