### ISSUE TITLE
SBT3 is complaining about local changes being overwritten

### ISSUE THREAD

**Issue by diek** [SideBarEnhancements-org/SideBarEnhancements#338]
![Error Message](https://cloud.githubusercontent.com/assets/1261158/19413301/8a7fab20-92ff-11e6-8aa1-6fab596a6900.png)

**Comment by titoBouzout** [comment]
You trying to do a pull from a git repo that has uncommited changes.

**Comment by diek** [comment]
Tito, I copied the repo about a 7-10 days ago. Should I just delete the existing folder and download it again?

**Comment by titoBouzout** [comment]
Probably
