### ISSUE TITLE
Not able to edit settings. 

### ISSUE THREAD

**Issue by MercuryxLion** [SideBarEnhancements-org/SideBarEnhancements#339]
I'm new using sublime text, so I'm not used to modify settings of the packages, but I want to set the default browser to chrome, but I can't do it. I suppose that I need to create a new .json file with the settings for "user", not "default". But when I do it, it only works during a few secs, after that, the default file apparently take control over the settings. How can I solve this?

**Comment by titoBouzout** [comment]
Hi, In theory if you go to 

1. Main menu bar 
2. Preferences
3. Package Settings
4. Sidebar
5. and click Settings - Users

Any change made to that file will overwrite any default settings (if the new setting is valid). As far as I know works as expected. Please be sure that no other package is messing with settings, and in any case please paste here the content of the problematic file (The complete content)

**Comment by MercuryxLion** [comment]
Thank you a lot for your reply, finally I realized how to modify the settings (It was all my fault). Now I would like to modify these specific settings: 

 

- **Open with browser** (So I can delete all the options except _chrome, opera and firefox_. Yes, even _open in all browsers and default_). Do you know how can I do it?

- **Open with**( So I can delete the option of Edit applications or at least show it the last in the list).


Thank you for your support, I will donate asap.

**Comment by titoBouzout** [comment]
Unless you are willing to edit the menu directly there's no programmatically way to hide a complete menu, you can hide all menu items, but ST will not hide the menu. I guess they will add the "is_visible" command flag at some point
