### ISSUE TITLE
why has `aaaaa_side_bar`

### ISSUE THREAD

**Issue by zce** [SideBarEnhancements-org/SideBarEnhancements#341]
https://github.com/SideBarEnhancements-org/SideBarEnhancements/blob/st3/Side%20Bar.sublime-menu#L2-L9

**Comment by titoBouzout** [comment]
Good question, Sublime Text does not provide an "onpopupshowing" event. So when a menu is opened you have no way to do some preprocessing (for example get extended information about the selected files and folders).  So what this command does is to emulate  "onpopupshowing" by collecting all the needed information for the next commands to use.
