### ISSUE TITLE
Cannot create new file from right-click menu

### ISSUE THREAD

**Issue by laurenbenichou** [SideBarEnhancements-org/SideBarEnhancements#343]
After installing SideBarEnhancements, I find myself unable to create new file by right-clicking on a folder. I click on 'New File' and nothing happens. No errors in the ST console. I removed the package and it seems to work again. 

![screen shot 2016-11-02 at 11 19 11 am](https://cloud.githubusercontent.com/assets/5431395/19941656/39c05926-a0ee-11e6-842b-d99b94265591.png)

I am on a Mac running 10.11.2 OSX El Capitan. Running ST3, Build 3126. 

Thanks for the help!

**Comment by titoBouzout** [comment]
Hi there you still have this problem? I guess Build 3126 is a typo because last one seems to be 3125.  Also there's no other reports..... maybe an installation problem

**Comment by laurenbenichou** [comment]
I am still having this problem, yes. And not a typo. At least not a typo on my part.

![screen shot 2016-11-15 at 11 15 11 am](https://cloud.githubusercontent.com/assets/5431395/20319922/d0c300fe-ab24-11e6-983f-a1b93c38172a.png)

**Comment by titoBouzout** [comment]
Oh I see, you using 
http://www.sublimetext.com/3
I was checking 
http://www.sublimetext.com/3dev

Umm, ok, can you please:
1. open the console with Menu - View - Show console
2. install the package
3. Try to create a file. 

A tiny popup should appear on bottom asking the file name. 
If the popup appears, can you please type something, then enter. 
Then if still does not work, can you please copy and paste the content of the console on this issue

Thanks!

**Comment by laurenbenichou** [comment]
Hey! So, I've removed the package. Open the console. Re-installed the package. No issue. I right-click to create a new file, the console disappears and nothing happens. I think that the new file creation process might be  working but the small pop-up that usually appears at the bottom in order to enter the new file's name doesn't show up. When I remove SideBarEnhancement, it works BUT I can also try to remove the theme I am using? Maybe it's a combination of packages...

```
ignored packages updated to: ["SideBarEnhancements", "Sublimerge Pro", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Sublimerge Pro", "Vintage"]
reloading settings Packages/SideBarEnhancements/Side Bar.sublime-settings
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by titoBouzout** [comment]
Yes, thats the problem. For some reason the popup is not shown, or maybe is shown but the default size is invisible, maybe you can try to resize it (if you see something down there.....)

**Comment by titoBouzout** [comment]
This is theme issue.
