### ISSUE TITLE
Documentation does not warn statistics are sent somewhere

### ISSUE THREAD

**Issue by nMustaki** [SideBarEnhancements-org/SideBarEnhancements#345]
Hi,

I love SideBarEnhancements, but I think you __must__ advertise you are collecting data. Especially when the collecting code is crashing the plugin !

**Comment by nMustaki** [comment]
PR to fix this #347

**Comment by titoBouzout** [comment]
Well yes, I agree, says on top of the file with a clear file name. Adding it to the readme would be nice too. Im merging your requests
