### ISSUE TITLE
Feature Request: Collapse all, Expand all

### ISSUE THREAD

**Issue by mayeenulislam** [SideBarEnhancements-org/SideBarEnhancements#350]
The title says it all, I have feature request:

Could you please add the following features:

- Collapse all directories
- Expand all directories

Currently I'm using `.sublime-project` for doing this. I change something, save the file, that collapses all the directories. Then I undo the changes made to the project file. 😄

**Comment by titoBouzout** [comment]
Hi there! Nice hack! You can do same with ALT+CLICK on a folder

**Comment by mayeenulislam** [comment]
Just to make the answer bold, the shortcut key combination is:
<kbd>Alt</kbd> + <em>`click`</em> the directory
