### ISSUE TITLE
"New File"/"New Folder" text prompt appears on wrong window

### ISSUE THREAD

**Issue by potato20** [SideBarEnhancements-org/SideBarEnhancements#351]
Copying and pasting from SublimeTextIssues/Core#1520

Summary

"new file"/"new folder" text box appears on another window
### Summary
"new file"/"new folder" text box appears on another window

### Expected behavior
When i click "new file"/"new folder" on a window with one project loaded, i expect to see the text box prompting me for the name of the new file/folder in the same window.

### Actual behavior
The text box appears on another window.

### Steps to reproduce

1. Open a project in sublime text 
2. Open a new sublime text window (ctrl + shift + n) and switch to some other project in that new window
3. In the first window, right click on any directory inside your project and click "new file" or "new folder"
4. Observe that the text box to enter the name of the new file/folder appears on the second window

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ ] Mac OS ...
  * [X] Linux ...
* Sublime Text:
  * Build 3126

**Comment by titoBouzout** [comment]
I could try to change the referenced window to self.window but sublime is obviously misbehaving by giving the wrong window to sublime.active_window() call, this also I cannot repro on windows. Not sure why was closed the other bug, looks very valid to me, even if theres "yet another workaround"

**Comment by titoBouzout** [comment]
hi there @potato20 I tried to apply the workaround and in any case fallback to previous behaviour. Can you please test the exact same thing to let me know if now works as expected on Linux. Many thanks!
