### ISSUE TITLE
Rename won't work at all

### ISSUE THREAD

**Issue by alvarotrigo** [SideBarEnhancements-org/SideBarEnhancements#352]
Renaming files won't work.

![rename](https://cloud.githubusercontent.com/assets/1706326/21385217/a267992e-c765-11e6-9d70-4de748e55a0f.JPG)

### Expected behavior
Rename of the file

### Actual behavior
The status bar shows "Renaming..." and never ends. 

### Steps to reproduce

1. Right click on the file to rename.
2. Select "Rename"
3. Write the new name
4 Press enter

### Environment
* Operating system and version:
  * [ ] Windows 7.

* Sublime Text:
  * Build 3126

Console showing:

> DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/trigoa/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/trigoa/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/trigoa/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Dayle Rees Color Schemes", "Vintage"]
pre session restore time: 0.130442
startup time: 0.151442
first paint time: 0.152442
first paint time: 0.152442
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Expand Tabs on Save.ExpandTabsOnSave
reloading plugin LiveReload.livereload_st2
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "livereload_st2 in C:\Users\trigoa\AppData\Roaming\Sublime Text 3\Installed Packages\LiveReload.sublime-package", line 21
    except Exception, u:
                    ^
SyntaxError: invalid syntax
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin JSHint Gutter.JSHint
reloading plugin LiveReload.__init__
reloading plugin LiveReload.CoffeescriptPlugin
reloading plugin LiveReload.CommandAPI
reloading plugin LiveReload.CompassPlugin
reloading plugin LiveReload.LESSPlugin
reloading plugin LiveReload.LiveReload
reloading plugin LiveReload.SimpleReloadCallback
reloading plugin LiveReload.SimpleReloadPlugin
reloading plugin LiveReload.SimpleReloadPluginDelay
reloading plugin LiveReload.SimpleWSCallback
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
LiveReload: added file /livereload.js with content-type: text/javascript
INFO:WebSocketClient:Starting server
Package Control: Skipping automatic upgrade, last run at 2016-12-21 09:51:10, next run at 2016-12-21 10:51:10 or after
Exception in thread Thread-7:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "SideBar in C:\Users\trigoa\AppData\Roaming\Sublime Text 3\Installed Packages\SideBarEnhancements.sublime-package", line 1189, in run
TypeError: Window() missing 1 required positional argument: 'window'

> reloading settings Packages/User/SublimeLinter.sublime-settings
Exception in thread Thread-8:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "SideBar in C:\Users\trigoa\AppData\Roaming\Sublime Text 3\Installed Packages\SideBarEnhancements.sublime-package", line 1189, in run
TypeError: Window() missing 1 required positional argument: 'window'

**Comment by Fire-Dragon-DoL** [comment]
Confirmed facing the same issue on OSX Yosemite. Temporary disabled sidebar enhancements

**Comment by loweoj** [comment]
Any on OSX El Capitan

**Comment by titoBouzout** [comment]
Thanks, fixed in https://github.com/SideBarEnhancements-org/SideBarEnhancements/commit/57e07c338e707335a74abef4017426bf85d1aa67

**Comment by alvarotrigo** [comment]
@titoBouzout when should we expect it to be fixed in our application?

**Comment by titoBouzout** [comment]
I think updating the package should be enough.
