### ISSUE TITLE
Empty menu is left over after uninstalling package

### ISSUE THREAD

**Issue by Gabriel-p** [SideBarEnhancements-org/SideBarEnhancements#354]
I uninstalled this package and an empty menu was left behind:

![captura realizada el 2016-12-28 12 16 26](https://cloud.githubusercontent.com/assets/6054951/21524806/c41409e4-ccf7-11e6-8af2-27ab01fad246.png)

How do I completely remove the package?

**Comment by CollinDaugherty** [comment]
delete the folder in  AppData\Roaming\Sublime Text 3\Packages\User

**Comment by Gabriel-p** [comment]
Thank you. The folder was in `~/.config/sublime-text-3/Packages/User/` btw.
