### ISSUE TITLE
Add option to disable file preview when right-clicking a file

### ISSUE THREAD

**Issue by rfgamaral** [SideBarEnhancements-org/SideBarEnhancements#355]
Basically what the title says...

Currently, left-clicking/right-clicking a file in the sidebar, previews that file (given the `preview_on_click` Sublime option is set to `true`). It would be nice to have an option on the sidebar to force this behavior just for the left/right click, instead of both.

This would prevent a file preview when one wants to just delete the file independently of the contents.

**Comment by titoBouzout** [comment]
Hi thanks, We know about this, but there's no way to configure it, maybe..... someday this can be closed https://github.com/SublimeTextIssues/Core/issues/2
