### ISSUE TITLE
Data collection

### ISSUE THREAD

**Issue by gerardroche** [SideBarEnhancements-org/SideBarEnhancements#359]
Add a "submit_usage" setting like Package Control https://github.com/wbond/package_control/blob/master/Package%20Control.sublime-settings#L32.

Disappointed on the move to collect usage data. Opt-in would have been a better move.

**Comment by titoBouzout** [comment]
Thanks, I put a note about it, I understand you prefer opt-in but at the same time I guess you understand why wasnt done that way. thanks
