### ISSUE TITLE
Give 20$

### ISSUE THREAD

**Issue by timpler** [SideBarEnhancements-org/SideBarEnhancements#361]
I've donated quite a few projects in my life and I believe that this is not the way to do that:

![image](https://cloud.githubusercontent.com/assets/7311462/23616002/93be4bee-0288-11e7-8b07-4bda11a6f0f1.png)

Every time I right click in my side bar or perform some peer programming, I see this and it looks like I'm using some tools from torrents.

**Comment by titoBouzout** [comment]
OK, not sure what you mean with torrents, I don't use torrents, but thank you.

**Comment by diego898** [comment]
I agree with @timpler - I think this is **UNACCEPTABLE** - I will uninstall this plugin.

**Comment by pietrasiak** [comment]
Just in case - https://github.com/SideBarEnhancements-org/SideBarEnhancements/blob/807b9232e644968194dd30fd4fa36a6d45ad436e/Side%20Bar.sublime-menu#L745

**Comment by qraynaud** [comment]
I can understand the basic motivation, but at least provide an option to remove it. This takes place in a day to day tool!

**Comment by qraynaud** [comment]
Ok, there is one. I should learn how to read :-).

Add to your sidebar configuration :
```
  "i_donated_to_sidebar_enhancements_developer": "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=DD4SL2AHYJGBW"
```

**Comment by murilolivorato** [comment]
ridiculus , this beg for $20 dolars inside the application .

**Comment by Ordiel** [comment]
didn't work for me, uninstalling...
