### ISSUE TITLE
How can I  sync project sidebar with currently active file?

### ISSUE THREAD

**Issue by MOONLIGHTV** [SideBarEnhancements-org/SideBarEnhancements#364]
For example: 
At the start, a folder named scripts is closed
If I use [ctrl+p] to search and open  index.js in  scripts folder.

Then the file of index.js  is currently active now.

So, can I let the scripts folder in sidebar open and auto-sync to the currently active index.js?

**Comment by titoBouzout** [comment]
I think you are refering to https://github.com/SublimeTextIssues/Core/issues/301 and https://github.com/SublimeTextIssues/Core/issues/302 

The complete autofocus/autoselect/autoexpand-collapse in sidebar is really annoying and seems to me we cant do much about it.
