### ISSUE TITLE
Opt out on Windows?

### ISSUE THREAD

**Issue by rmenessec** [SideBarEnhancements-org/SideBarEnhancements#365]
Hi! How do I opt out of statistics collection on Windows, there not being a system-wide "~" expansion for the home directory?

Is it simply %UserProfile%, or should the file be created somewhere under %AppData%? How can I test that it's working?

Thanks!

**Comment by gpresland** [comment]
Git Bash defaults `~` to `%USERPROFILE%` so looks like if you run:

```bash
touch ~/.SideBarEnhancements.optout
```

in Git Bash you'll have the file created at `%USERPROFILE%/.SideBarEnhancements.optout`.
