### ISSUE TITLE
Remove donation item

### ISSUE THREAD

**Issue by gjjones** [SideBarEnhancements-org/SideBarEnhancements#366]
Is there a setting to remove the donation item from the bottom of the menu?

![image](https://user-images.githubusercontent.com/2683203/27231980-77a355a4-5282-11e7-8dab-7ba5d8bc8c8f.png)

**Comment by georgeperez** [comment]
If you donated, you can disable the donation box in the package settings for the User.

**Comment by GiancarloGomez** [comment]
Currently any option you put on the user settings are ignored. At least that is what I am experiencing

**Comment by georgeperez** [comment]
Not here. Read the instructions carefully! ![](http://i.imgur.com/E5C1vYG.png)

Later modify them in your settings for User.

**Comment by GiancarloGomez** [comment]
I did but for me I see no change on my Mac. I did notice that some other settings are working after I cleaned up but setting true to the "i_donated_to_sidebar_enhancements_developer" setting still keeps it in view.

**Comment by GiancarloGomez** [comment]
![screen shot 2017-07-13 at 1 27 20 pm](https://user-images.githubusercontent.com/152279/28179157-10558702-67cf-11e7-9f54-60a9e470b823.png)

**Comment by georgeperez** [comment]
Again, you're not reading the instructions carefully. Read the comment. It doesn't say to change the value to true.

**Comment by GiancarloGomez** [comment]
Holy crap, I am so embarrassed. I failed to do what I complain about the most, people not reading. I am sorry apparently this was an ID 10 T error :-)
