### ISSUE TITLE
Removal from Default Package Control Channel

### ISSUE THREAD

**Issue by wbond** [SideBarEnhancements-org/SideBarEnhancements#367]
It appears this package has potentially been sending proprietary information via installed package names to the company Kite. As an attempt to prevent further invasion of privacy, I've removed the package from the default channel.

Kite has indicated they are going to request you remove the stats collection feature. Once you have, then we can discuss adding it back.

In the mean time there is a good chance I'll replace it with a fork notifying users of the potential private information sent to Kite, and the stats removed.

**Comment by wbond** [comment]
This has been added back: https://packagecontrol.io/packages/SideBarEnhancements with the new version that has the collection removed. Everyone should be updating to this version as they restart Sublime Text.

**Comment by fooey** [comment]
@wbond So the lesson here is that an package getting caught being bribed by a 3rd party to inject malevolent code just needs to revert the code and everyone's happy?

@titoBouzout is **every** bit as much to blame for this situation as the Kite organization. What reason is there to trust that this won't just happen again when someone opens their checkbook even wider?

Allowing this sort of behavior to stand is a complete abdication of the implicit responsibility to protect the community.

**Comment by wbond** [comment]
@fooey I think the best place to discuss this is probably at https://forum.sublimetext.com/t/rfc-default-package-control-channel-and-package-telemetry/30157, just because of the pure number of people reading it. I am definitely open to hearing how you think my reaction/handling of this should be different.

**Comment by diego898** [comment]
I agree with @fooey, has @titoBouzout ever provided any explanation? I don't see any in the sublime forum either.
