### ISSUE TITLE
Expanded folders collapse when hiding a folder from sidebar

### ISSUE THREAD

**Issue by leonklingele** [SideBarEnhancements-org/SideBarEnhancements#370]
### Steps to reproduce

1. Open a project which contains multiple nested folders
2. Open some of them
3. Right click on one of the folders and select `Hide From Sidebar (In theory exclude from project)` 

### Expected result

- Folder should disappear without collapsing any open folders

### Actual result

- All open folders are closed

**Comment by titoBouzout** [comment]
Hi there unfortunately there no way to prevent that from happening.

**Comment by leonklingele** [comment]
I'm going to report an issue @ upstream, i.e. the Sublime repo. Is it this API call you're using to hide the item? `side_bar_project_item_exclude`

**Comment by titoBouzout** [comment]
I been searching for the bug here https://github.com/SublimeTextIssues/Core/issues but cant find it. SBE changes the project json as theres no API call to remove a folder.
