### ISSUE TITLE
Use a more natural sort order for file names

### ISSUE THREAD

**Issue by heliodor** [SideBarEnhancements-org/SideBarEnhancements#371]
Currently, the sort order is, for example:

```
- (dash/minus)
0-9
= (equal sign)
_ (underscore)
A-Z
a-z
```

A more natural sort order would provide more utility. For example, we can keep alphanumeric characters in a contiguous block.

Personally, I consider the alphanumeric sort order to be 0-9 a-Z A-Z. Numbers come before letters, and uppercase is a bigger "value" than lowercase. I also consider the various keyboard characters to come before numbers; therefore, underscore, dash, parentheses and so on come before 0-9. That way you can "pin" a special item at the top of a long list by starting its name with an underscore:

```
_something_special.txt
02379823.csv
... (many items)
92342343.csv
aqwekljr.csv
... (many items)
zqwkjer.csv
AHUIKJ.csv
... (many items)
ZQWJKEJNK.csv
```

**Comment by titoBouzout** [comment]
https://github.com/SublimeTextIssues/Core/issues/328 :)

**Comment by titoBouzout** [comment]
This is unfortunately not customizable.  I added a comment in the ST issue asking for custom sorting functions so everyone can sort as they wish

**Comment by heliodor** [comment]
Okay, for some reason I thought the whole sidebar belongs to this plugin once installed. But yes, it makes sense that the sidebar is still handled by ST and the issue belongs with them.

Thank you for linking the issues. I'll close this issue as there's nothing further to be done.
