### ISSUE TITLE
Include cursor's line number in copied path

### ISSUE THREAD

**Issue by andersennl** [SideBarEnhancements-org/SideBarEnhancements#372]
I use the command `side_bar_copy_path_absolute_from_project` to copy the path to the currently opened file. I was wondering if there's any option to append the current line number, to get an output like: `/spec/models/some_spec.rb:32`. Thanks!

**Comment by titoBouzout** [comment]
There been implemented you will need to enable it via settings

**Comment by andersennl** [comment]
I see, thanks!

**Comment by titoBouzout** [comment]
yw
