### ISSUE TITLE
"Open with" User Settings not loaded

### ISSUE THREAD

**Issue by kontrafiktion** [SideBarEnhancements-org/SideBarEnhancements#375]
I opened the User settings as described in #339
The following are the contents of my (user) settings file:

```
[
  {"id": "side-bar-files-open-with",
    "children":
    [
      {
        "caption": "iThoughtsX",
        "id": "side-bar-files-open-with-chrome",

        "command": "side_bar_files_open_with",
        "args": {
                  "paths": [],
                  "application": "iThoughtsX",
                  "extensions":"mmap", //any file with extension
                  "args":[]
            },
        "open_automatically" : false // will close the view/tab and launch the application
      }

    ]
  }
]
```
But it seems like the User settings are not loaded.

1. If I _add_ the `{ "caption": "iThoughtsX" ...` stuff to the global settings it works.
2. If I copy the global settings (with the iThoughtsX-Stuff) to the user settings and remove the iThoughtsX from the global settings it does not work anymore

What am I missing?

**Comment by titoBouzout** [comment]
you need to:
1. right click the sidebar
2. "open with"
3. Edit Applications

there you paste the content of your json :)

Because you are editing a menu directly, you aren't changing preferences.
