### ISSUE TITLE
The file cannot be saved in the current directory

### ISSUE THREAD

**Issue by qzhaoleilei** [SideBarEnhancements-org/SideBarEnhancements#378]
(Sorry,My English sucks)

If , i create a new file in  /goods/   folder (use  ctrl+n ) , but save it will be other foler;

when i remove this plugin, it's ok.

why?

example:

current edit file is /goods/info.js , on info.js use ctrl+n create a new file , save the new file, the new file should  saved be /goods/ folder.  but, it not?
when i remove SideBarEnhancements , it's ok.

**Comment by titoBouzout** [comment]
Please see #379
