### ISSUE TITLE
"new file/new folder", it spends very long time to do this. And sublime will be not working...

### ISSUE THREAD

**Issue by win7killer** [SideBarEnhancements-org/SideBarEnhancements#380]
When I right click at the sidebar, 
choose "new file/new folder"，the sidebar is not refresh the new file at moment, it take a long time(about 3-5s, sometime more), 
and sometime sublime will be notworking(busy), I can do nothing, just wait before it works.  

I had try to remove all packges , just install SideBarEnhancements, and it's not better~

OS: mac 10.13.1 && mac 10.11+

Wating the solve...

**Comment by titoBouzout** [comment]
Not related to this package, report it in https://forum.sublimetext.com
