### ISSUE TITLE
Add new file/folder doesn't focus on input field at the bottom

### ISSUE THREAD

**Issue by dingo-d** [SideBarEnhancements-org/SideBarEnhancements#382]
It's been happening since day one, but I was just too lazy to report it - when you click on add new file or folder the input field at the bottom isn't highlighted, so if I was in a terminal, or in some other program, and clicked add new file in Sublime and started typing, I would be typing in this program instead of the input field inside Sublime.

Can this be added? The same would have to work for renaming, moving and find action.

**Comment by titoBouzout** [comment]
I believe this problem is because you have enable "drag_text", ST slightly thinks you are dragging text if your mouse move a very little from between your mousedown and mouseup events...

**Comment by dingo-d** [comment]
Never knew there was an action for that, the drag text thing always annoyed me! Thanks! :)
