### ISSUE TITLE
Git on sidebar

### ISSUE THREAD

**Issue by godey4me** [SideBarEnhancements-org/SideBarEnhancements#385]
How do I get `Git` to appear in my sidebar menu?
![2018-02-05_11-39-23](https://user-images.githubusercontent.com/19440061/35822374-51f7c5a2-0a69-11e8-9c81-cf5f47292f1e.jpg)
 I have searched but cannot seem to have it appear. The last item I have i Give$.
Thanks

> ``

**Comment by titoBouzout** [comment]
https://github.com/titoBouzout/SideBarGit
