### ISSUE TITLE
Custom command program with "Open/Run"

### ISSUE THREAD

**Issue by russellstrauss** [SideBarEnhancements-org/SideBarEnhancements#386]
By default, Open/Run can open a folder with Powershell or cmd.exe depending on the user settings. How can we change the path of the "Open/Run" program to use a different terminal that is not cmd.exe or Powershell?

**Comment by titoBouzout** [comment]
Now you can tell which program to use with a new setting named "use_command". The command should be on path, Im not really sure if this will be enough for you just let me know.

https://github.com/SideBarEnhancements-org/SideBarEnhancements/commit/da7526c1487502b0f4765db2376b902def89484f#diff-0d4da8d8bf21ca5c7236c26ee23971e2R520
