### ISSUE TITLE
Right click on tab - add show in sidebar?

### ISSUE THREAD

**Issue by dingo-d** [SideBarEnhancements-org/SideBarEnhancements#388]
Is it possible to add a feature that when you have an open file in a tab that you opened from search, for instance, to have 'Show in sidebar'? So that the file is expanded and highlighted in the sidebar?

Would be a cool feature :)

**Comment by titoBouzout** [comment]
Added the functionality as "Locate" instead of "Reveal" as Reveal is already used to show the selected files via the file explorer of each system.
