### ISSUE TITLE
"Copy path relative to project" should not have a leading slash

### ISSUE THREAD

**Issue by maxrothman** [SideBarEnhancements-org/SideBarEnhancements#389]
As the title says. A common use case for this feature is to paste the copied path(s) into the terminal, and here, a leading slash is always incorrect. It's also semantically confusing: a leading slash (in UNIX-land at least) always connotes an absolute path, and by the name of the command, a user would expect to get a relative path.

I'm happy to contribute this change, I'd implement it by trimming the leading slash [here](https://github.com/SideBarEnhancements-org/SideBarEnhancements/blob/st3/SideBar.py#L836), but I wanted to make sure you were on board with it first.

**Comment by titoBouzout** [comment]
Hi! Commands that name "relative" do not have a leading slash. You may mean "Copy Path From Project" which is intended for web use and does not mention relative :P

**Comment by titoBouzout** [comment]
In any case you please give me some steps to follow so I can see clearly what the problem is, thanks!

**Comment by maxrothman** [comment]
Sure, here's my workflow:

* Have a project open and a file in that project
* Open the command palette and select "Copy Path From Project"
* Go to the terminal, type `git add`, then paste. You get:
    ```
    git add /path/to/file
    ```
Now I have to go trim off that leading slash to make the command valid.

**Comment by titoBouzout** [comment]
Thank you, now there's a relative option
