### ISSUE TITLE
Operations on folders works but aren't visible

### ISSUE THREAD

**Issue by rozzilla** [SideBarEnhancements-org/SideBarEnhancements#390]
Hi folks and congratulations for this extension, it's really useful for me! :+1: 

I've found only issues doing operations on folders, such as delete, create, rename.

In a few words, the operation works correctly, but I don't see the changes on Sublime also if I refresh many times on the parent or the root folder.
If a take a look at the normal OS's folder explorer, I can see the modify.

**Comment by titoBouzout** [comment]
Hi! Thanks for the report, sublime text is buggy... I cannot really do much about that, I suggest to report the issue to https://forum.sublimetext.com
