### ISSUE TITLE
Wild about SideBarEnhancements, cannot install it properly by myself

### ISSUE THREAD

**Issue by ColorSquid** [SideBarEnhancements-org/SideBarEnhancements#391]
Hey :-D

I am new to github and sublime text.
I try to install SideBarEnhancements because people are 'wild' about it on the internet. :-D
However, cannot do it.

I installed Sublime and Github, than doing _Clone a respository_ > _URL_ and _Local Path_ , but the _...Roaming\Sublime Text 3\Packages_ already exists. I made a new folder called _SideBarEnhancements_ . When cloning, it does not work or something when opening Sublime Text, same with manual installment.

What can I do to solve this?

Kind regards,
Terken

**Comment by BarbzYHOOL** [comment]
For me, when I install it, it changes literally nothing :'( so not working

**Comment by titoBouzout** [comment]
https://forum.sublimetext.com/
