### ISSUE TITLE
Entire UI slowed down when on network drive

### ISSUE THREAD

**Issue by adinklotz** [SideBarEnhancements-org/SideBarEnhancements#396]
The entire UI is significantly slowed down when this package is active.  I first noticed this with the command palette: When SideBarEnhancements is enabled, the command palette takes 2-3 seconds to open, whereas it became nearly instant when I disabled the package.  I understand that certain operations, such as folder menus, should be expected to slow down when a network file is open, as the package has to pull file info over the relatively slow internet connection.   However, so far as I know, there's no good reason for not file-related or sidebar-related components like the command palette to experience any slowdown there.

Using: SideBarEnhancements v5.0.18
Sublime Text v 3.1.1

**Comment by titoBouzout** [comment]
Ill take a look this week

**Comment by titoBouzout** [comment]
>  I understand that certain operations, such as folder menus, should be expected to slow down when a network file is open, as the package has to pull file info over the relatively slow internet connection. However, so far as I know, there's no good reason for not file-related or sidebar-related components like the command palette to experience any slowdown there.

The SBE command palette does similar things to when you right click a networked file. Gatters information about the current view (which in your case is networked)

I was able to speed up (calculate stuff for the current selected files/folders on sidebar) by running a hidden command that works as a "onpopupshowing" caching that information for usage on all the following commands.

https://github.com/SideBarEnhancements-org/SideBarEnhancements/blob/da7526c1487502b0f4765db2376b902def89484f/SideBar.py#L135

That was like 3 years ago, if I remember correctly there was no way to implement the same caching for the command palette. Ill revisit the issue and will try to remove anything that slow it down for no real gains, but I may not be able to do it.  One suggestion is to just delete the Commands.sublime-commands from SBE (if you dont use the command palette frequently)
