### ISSUE TITLE
[Request] Add firefox developer edition

### ISSUE THREAD

**Issue by duranivan** [SideBarEnhancements-org/SideBarEnhancements#397]
Hi and thanks for an awesome package!

Would it be possible to add 'Firefox Developer Edition' to the list of supported browsers in `open_all_browsers` settings?

Thanks in advance!

**Comment by titoBouzout** [comment]
Im adding it for windows, if you use linux or OSX please let me know on which path is installed.

**Comment by titoBouzout** [comment]
Its been added here https://github.com/SideBarEnhancements-org/SideBarEnhancements/blob/44d3f9b4a512f116c2d043f13438f2b977c26961/SideBar.py#L2466  we just need to append there the paths were it could be found

**Comment by duranivan** [comment]
Thanks for this. I am in Mac and it can be open with `open -a Firefox\ Developer\ Edition`. So basically in your `SideBar.py` it would be:

```
 elif browser == "firefox-developer-edition":
            if sublime.platform() == "osx":
                items.extend(["open"])
commands = ["-a", "/Applications/Firefox\ Developer\ Edition.app", url]
```

Hope this helps.

**Comment by titoBouzout** [comment]
Thanks for the information!

**Comment by titoBouzout** [comment]
Updated to include the path for OSX. I removed the quotes Im not completely sure but I think popen already escaping on parameters. In case it does not work, can you please let me know so I add the quotes back. Thanks!
