### ISSUE TITLE
how to use open with to do a pipenv command which little bit complex ...

### ISSUE THREAD

**Issue by 2anyone** [SideBarEnhancements-org/SideBarEnhancements#401]
I would like implement the follow command when I right click `filename.ui` and do an open with:

`pipenv run python -m PyQt5.uic.pyuic filename.ui -o filename.py` 

how can I achieve this by set up an open with in `Side Bar.sublime-menu`?

and I don't know  how to get the **filename** part without ext from *.ui file and use it in output file.

I do checked there is "$NAME", but don't know how to use it and it seems had ext with it. 

if you can give me a example, that will be great. thanks.

**Comment by titoBouzout** [comment]
1. Right-click on any file in an open project and select from the menu "Open With" > "Edit Applications..."
2. Then as children you add something in the lines of `

```
//application 1
{
	"caption": "Fancy Python",
	"id": "side-bar-files-open-with-fancy-python",
	"command": "side_bar_files_open_with",
	"args": {
		"paths": [],
		"application": "", 
		"extensions": ".*", //any file with extension
		"args": [
			"pipenv",
			"run",
			"python",
			"-m",
			"PyQt5.uic.pyuic",
			"$NAME",
			"-o",
			"$NAME_NO_EXTENSION"
		]
	},
	"open_automatically": false // will close the view/tab and launch the application
}

```

Im adding now the "$NAME_NO_EXTENSION" so you will have to update to use the var that gives the file name without the extension

**Comment by titoBouzout** [comment]
https://github.com/SideBarEnhancements-org/SideBarEnhancements/commit/657a7b9ef4ffbec226e1360bcd73f3694edece05
